services:
  api_ai:
    container_name: api_ai
    build: 
      context: ./api_ai
      dockerfile: Dockerfile
    env_file: ./api_ai/.env
    ports:
      - "8000:8000"
    networks:
      - rag_network
    restart: always
  
  crawler:
    container_name: crawler
    build: 
      context: ./crawler
      dockerfile: Dockerfile
    env_file: ./crawler/.env
    volumes:
      - ./chroma_db:/opt/data/chroma_db
      - ./errors:/opt/data/errors
    networks:
      - rag_network
    depends_on:
      - api_ai

    rag:
      container_name: rag_component
      build:
        context: ./rag
        dockerfile: Dockerfile
      env_file: ./rag/.env
      networks:
        - rag_network
      depends_on:
        - api_ai

networks:
  rag_network:
    name: rag_network
    driver: bridge