services:
  api_ai:
    container_name: api_ai
    build: 
      context: ./api_ai
      dockerfile: Dockerfile
    env_file: ./api_ai/.env
    ports:
      - "8000:8000"
    networks:
      - rag_network
    restart: always

networks:
  rag_network:
    name: rag_network
    driver: bridge